### ISSUE TITLE
SynopticGWT Tutorial

### ISSUE THREAD

**Issue by michelalbonico** [ModelInference/synoptic#410]
Dear developers,

Only reporting a tutorial inconsistency. The command "ant deployment-war" doesn't work when using the latest version (default git clone).

I've checked out a former commit (b08f7b9bad3c2f8bb746196bfb5eaa8366ad5719), which dates before the last tutorial's edition (4th of May 2015), and it's worked well.

Michel

**Comment by bestchai** [comment]
Hi Michel, thanks for reporting. I added a note to the top of the "Deploying SynopticGWT onto a server" section, here:
https://github.com/ModelInference/synoptic/wiki/DocsInstallation

Let me know if you run into any more issues.
