### ISSUE TITLE
Either remove http://synoptic.cs.washington.edu links or repair them

### ISSUE THREAD

**Issue by brunyuriy** [ModelInference/synoptic#412]
We link to http://synoptic.cs.washington.edu, for example here: https://github.com/ModelInference/synoptic/wiki
We should either have the redirect somewhere, or temporarily remove the references.  We hope to have the universal front end running soon, which could be a good place to link to.

**Comment by bestchai** [comment]
I think we should remove all refs and add ref to universal front-end once it is up. I did this for refs I could find; hopefully all of them.
