### ISSUE TITLE
Question: Installation issues

### ISSUE THREAD

**Issue by AlexandreEraclides** [ModelInference/synoptic#418]
I'm trying to install/build following the instructions given, but using ant synoptic or running the python script doesn't seem to do the trick. It always fails using the ant (/home/alexandre/Desktop/Work/synoptic/ant-util.xml:19: Execute failed: java.io.IOException: Cannot run program "hg" (in directory "/home/alexandre/Desktop/Work/synoptic/daikonizer"): error=2, No such file or directory
). It is necessary to use the java 1.7 or it can be a higher version? or it has something to do with issue #413 ?

Thanks, Alexandre

**Comment by bestchai** [comment]
Yes, this seems to be related to #413.

I just made a quick fix that should make your local version compile. It's not a complete fix, but it's a start:
https://github.com/ModelInference/synoptic/commit/db1f862eb2a59de1fe2efedf7224382b2983faa8

Try it out, and thanks for the issue report!

**Comment by AlexandreEraclides** [comment]
It worked, thank you for the help.
