### ISSUE TITLE
How to rewrite Biermann algorithm with InvariMint

### ISSUE THREAD

**Issue by TonyNEPU** [ModelInference/synoptic#421]
The KTails algorithm proposed by COOK has been already implemented with InvariMint. But this KTails is quite different from the original KTails proposed by Biermann (also called Biermann algorithm). I am wondering if the Biermann algorithm can be also rewrite using the declarative method used in InvariMint, and how?

**Comment by bestchai** [comment]
The TSE'15 [journal paper on InvariMint](https://www.cs.ubc.ca/~bestchai/papers/invarimint_tse15.pdf) includes a proof that the declarative kTails results in an FSM that has the same language as the FSM produces by the Cook kTails version. Given this, I'm not sure what you mean by _"if the Biermann algorithm can be also rewrite using the declarative method used in InvariMint"_.

**Comment by TonyNEPU** [comment]
What I mean is that I am going to implement the declarative Biermann algorithm with InvariMint. Biermann algorithm is actually the original KTails algorithm, it was proposed by Biermann and  Feldman in "On the Synthesis of Finite-State Manchines from Samples of Their Behavior".  So My question is how to implement declarative Biermann algorithm with InvariMint;-)

**Comment by bestchai** [comment]
Ah, right. The TSE paper focuses on Cook's kTail. I don't think I tried to express Biermann's kTail alg. with InvariMint. But, the InvariMint work was done a while back, so perhaps there was a reason for this choice. Good luck with getting it to go through. If you do come up with a formulation for Biermann's version, do submit a pull request.
